import Foundation

enum Supertype {
    case Basic
    case Legendary
    case Snow
}

enum Type {
    case Artifact
    case Creature
    case Enchantment
    case Instant
    case Land
    case Planeswalker
    case Sorcery
    case Tribal
}

enum Subtype {
    case Ajani
    case Angel
    case Antelope
    case Ape
    case Archer
    case Archon
    case Artificer
    case Assassin
    case Aura
    case Avatar
    case Basilisk
    case Bat
    case Bear
    case Beast
    case Berserker
    case Bird
    case Boar
    case Camel
    case Cat
    case Centaur
    case Chandra
    case Cleric
    case Construct
    case Crab
    case Crocodile
    case Cyclops
    case Davriel
    case Demon
    case Desert
    case Devil
    case Dinosaur
    case Djinn
    case Dragon
    case Drake
    case Druid
    case Dryad
    case Dwarf
    case Efreet
    case Egg
    case Elder
    case Eldrazi
    case Elemental
    case Elephant
    case Elf
    case Elk
    case Equipment
    case Faerie
    case Fish
    case Food
    case Forest
    case Fox
    case Frog
    case Fungus
    case Gargoyle
    case Garruk
    case Gate
    case Giant
    case Goat
    case Goblin
    case God
    case Golem
    case Gorgon
    case Griffin
    case Hellion
    case Hippo
    case Homarid
    case Homunculus
    case Horror
    case Horse
    case Hound
    case Huatli
    case Human
    case Hydra
    case Illusion
    case Imp
    case Insect
    case Island
    case Jace
    case Jackal
    case Jellyfish
    case Karn
    case Kaya
    case Kirin
    case Knight
    case Lammasu
    case Lizard
    case Merfolk
    case Minotaur
    case Monk
    case Mouse
    case Mountain
    case Mutant
    case Naga
    case Nightmare
    case Ninja
    case Nissa
    case Noble
    case Octopus
    case Ogre
    case Ooze
    case Orc
    case Owl
    case Ox
    case Pegasus
    case Phoenix
    case Pirate
    case Plains
    case Plant
    case Rat
    case Rhino
    case Rogue
    case Saga
    case Saproling
    case Satyr
    case Scarecrow
    case Scout
    case Serpent
    case Shade
    case Shaman
    case Sheep
    case Siren
    case Skeleton
    case Sliver
    case Snake
    case Soldier
    case Sphinx
    case Spider
    case Spirit
    case Squid
    case Swamp
    case Tezzeret
    case Thopter
    case Thrull
    case Treasure
    case Treefolk
    case Trilobite
    case Troll
    case Turtle
    case Ugin
    case Unicorn
    case Vampire
    case Vedalken
    case Vehicle
    case Viashino
    case Vivien
    case Wall
    case Warlock
    case Warrior
    case Weird
    case Wizard
    case Wolf
    case Wurm
    case Yeti
    case Zombie
}
