import Foundation

enum Supertype {
    case Basic
    case Legendary
    case Snow
}

enum Type {
    case Artifact
    case Creature
    case Enchantment
    case Instant
    case Land
    case Planeswalker
    case Sorcery
    case Tribal
}

enum Subtype {
    case Ajani
    case Angel
    case Antelope
    case Archer
    case Artificer
    case Assassin
    case Aura
    case Avatar
    case Basilisk
    case Bat
    case Bear
    case Beast
    case Bird
    case Boar
    case Camel
    case Cat
    case Centaur
    case Cleric
    case Construct
    case Crab
    case Demon
    case Desert
    case Devil
    case Dinosaur
    case Djinn
    case Dragon
    case Drake
    case Druid
    case Dryad
    case Dwarf
    case Efreet
    case Egg
    case Elder
    case Elemental
    case Elephant
    case Elf
    case Elk
    case Equipment
    case Faerie
    case Fish
    case Forest
    case Frog
    case Fungus
    case Gargoyle
    case Gate
    case Giant
    case Goblin
    case Golem
    case Griffin
    case Hellion
    case Homarid
    case Homunculus
    case Horror
    case Horse
    case Hound
    case Huatli
    case Human
    case Hydra
    case Illusion
    case Imp
    case Insect
    case Island
    case Jackal
    case Kirin
    case Knight
    case Lammasu
    case Lizard
    case Merfolk
    case Minotaur
    case Monk
    case Mountain
    case Mutant
    case Naga
    case Nightmare
    case Ogre
    case Orc
    case Ox
    case Pegasus
    case Phoenix
    case Pirate
    case Plains
    case Plant
    case Rat
    case Rhino
    case Rogue
    case Saga
    case Saproling
    case Satyr
    case Scarecrow
    case Scout
    case Serpent
    case Shade
    case Shaman
    case Skeleton
    case Snake
    case Soldier
    case Sphinx
    case Spider
    case Spirit
    case Swamp
    case Tezzeret
    case Thopter
    case Thrull
    case Treasure
    case Treefolk
    case Trilobite
    case Turtle
    case Unicorn
    case Vampire
    case Vedalken
    case Vehicle
    case Viashino
    case Vivien
    case Wall
    case Warrior
    case Wizard
    case Wolf
    case Wurm
    case Yeti
    case Zombie
}
