import Foundation

enum Supertype {
    case Basic
    case Legendary
    case Snow
}

enum Type {
    case Artifact
    case Creature
    case Enchantment
    case Instant
    case Land
    case Planeswalker
    case Sorcery
    case Tribal
}

enum Subtype {
    case Angel
    case Antelope
    case Archer
    case Artificer
    case Assassin
    case Avatar
    case Basilisk
    case Bat
    case Bear
    case Beast
    case Bird
    case Boar
    case Cat
    case Centaur
    case Cleric
    case Construct
    case Crab
    case Dinosaur
    case Djinn
    case Dragon
    case Drake
    case Druid
    case Dryad
    case Dwarf
    case Egg
    case Elemental
    case Elephant
    case Elf
    case Elk
    case Faerie
    case Fish
    case Forest
    case Frog
    case Fungus
    case Gargoyle
    case Gate
    case Giant
    case Goblin
    case Golem
    case Homarid
    case Horror
    case Human
    case Illusion
    case Insect
    case Island
    case Knight
    case Lizard
    case Merfolk
    case Minotaur
    case Monk
    case Mountain
    case Ogre
    case Orc
    case Pegasus
    case Pirate
    case Plains
    case Plant
    case Rat
    case Rhino
    case Saproling
    case Satyr
    case Scarecrow
    case Scout
    case Shade
    case Shaman
    case Skeleton
    case Soldier
    case Spider
    case Spirit
    case Swamp
    case Thopter
    case Thrull
    case Treefolk
    case Unicorn
    case Vampire
    case Vedalken
    case Wall
    case Warrior
    case Wizard
    case Wolf
    case Wurm
    case Zombie
}
